# Generated by Django 4.0.3 on 2022-04-07 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('post_short_description', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
                ('post_full_description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('post_author', models.CharField(max_length=20, verbose_name='Автор')),
                ('post_publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('post_slug', models.SlugField(default='', editable=False, max_length=100, unique=True)),
                ('post_is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
