# Generated by Django 4.0.3 on 2022-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Категория'),
        ),
    ]
