# Generated by Django 4.0.3 on 2022-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_is_featured',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
