# Generated by Django 4.0.3 on 2022-04-07 18:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=20, verbose_name='Автор'),
        ),
    ]
